name: torotoro_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # i18n
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  cloud_functions: ^6.0.2
  firebase_storage: ^13.0.2

  # Utilidades
  file_picker: ^10.3.3
  mime: ^2.0.0
  url_launcher: ^6.3.0
  http: ^1.2.2
  shared_preferences: ^2.3.3

  # Mapa
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # Login Google
  google_sign_in: ^5.4.4

  # Permisos/geo
  geolocator: ^13.0.2
  permission_handler: ^11.3.1

  # TTS
  flutter_tts: ^4.2.0

  # Reportes/visual
  fl_chart: ^0.69.2
  pdf: ^3.11.1
  printing: ^5.13.4
  
  # 🔥 QR Code para web
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # ✅ Activa gen_l10n (usará lib/l10n/*.arb)
  generate: true

# ✅ Assets - Imágenes
  assets:
    - assets/