// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'run the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'run the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'run the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBALmTAssdesZ6I5oIc86-EX9EEkGck6Vg',
    appId: '1:716625495055:web:582ac78a96078a2b0b4f7a',
    messagingSenderId: '716625495055',
    projectId: 'proyecttorotoro',
    authDomain: 'proyecttorotoro.firebaseapp.com',
    storageBucket: 'proyecttorotoro.firebasestorage.app',
    measurementId: 'G-S0VJ7QF71S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATkt-Nkem8DxUMyipQQvUFh24RT9-lPnU',
    appId: '1:716625495055:android:b717a4e59645cdfa0b4f7a',
    messagingSenderId: '716625495055',
    projectId: 'proyecttorotoro',
    storageBucket: 'proyecttorotoro.firebasestorage.app',
  );
}
